services:
  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/static:/var/www/static:ro
    depends_on:
      - qr_server
      - frontend
    networks:
      - qr_network
    restart: unless-stopped

  qr_server:
    build: ./qr_server
    container_name: qr_server
    ports:
      - "8080:8080"
    networks:
      - qr_network
    restart: unless-stopped

  db:
    image: postgres:17.7-trixie
    container_name: db
    volumes:
      - db_python:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_python:

networks:
  qr_network:
    driver: bridge