services:
  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./Códigos/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Códigos/frontend/static:/var/www/static:ro
    depends_on:
      - frontend
      - backend
    networks:
      - qr_network

networks:
  qr_network:
    external: true
